# Generated by Django 4.1.5 on 2023-02-20 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_admin_booking_customer_payment_receptionist_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Receptionist',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
