# Generated by Django 4.1.5 on 2023-03-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='search',
        ),
    ]
