# Generated by Django 4.1.5 on 2023-03-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_delete_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_image',
            field=models.ImageField(default='sorry no image available', upload_to='static/images'),
        ),
    ]
