# Generated by Django 4.1.5 on 2023-03-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_alter_room_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_image',
            field=models.ImageField(upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_no',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
