# Generated by Django 4.1.5 on 2023-03-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0004_alter_room_room_image_alter_room_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('King Size Four Poster', 'King Size Four Poster'), ('King Size Sleigh Bed', 'King Size Sleigh Bed'), ('Deluxe King Size', 'Deluxe King Size'), ('Deluxe Twin/Large Double', 'Deluxe Twin Large Double'), ('Compact Double', 'Compact Double'), ('Family Room', 'Family Room'), ('Single', 'Single')], default='Single', max_length=24),
        ),
    ]
