# Generated by Django 4.1.5 on 2023-03-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0005_alter_room_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_floor',
        ),
    ]
